<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>promise初体验</title>
</head>
<body>
  <div>
    <h2>Promise初体验</h2>
    <button id="btn">点击抽奖</button>
  </div>
  <script>
    //生成随机数
    function rand(m,n){
      return Math.ceil(Math.random() * (n-m+1)) + m-1
    }
    const btn = document.querySelector('#btn')
    btn.addEventListener('click',function(){
      // setTimeout(() => {
      // let n = rand(1,100)
      // if(n <= 30 ){
      //   alert('恭喜中奖了')
      // } else {
      //   alert('再接再厉')
      // }
      // }, 1000);

      //promise形式实现
      //注意这里构造实例对象时传入了一个函数，可以叫做执行器，执行器中传入的resolve,和reject都是Promise内部定义的
      // 执行器里的代码是同步执行的，立即执行
      const p = new Promise((resolve, reject) => {
        setTimeout(() => {
          let n = rand(1,100)
          if(n <= 30 ){
      //resolve 解决
      //reject 拒绝 这两个都是函数类型的数据
            resolve(n) //将 promise对象的状态设置为 “成功”
          } else {
            reject(n)  //将 promise对象的状态设置为 “失败”
          }
          }, 1000);
      })
      //调用then方法，可以对结果进行处理
      // 两个参数，一个是成功状态的回调，一个是失败的回调
      //两个回调方法还可以接受参数
      p.then((value) => {
        alert('恭喜你中奖了！中将数字为'+value)

      } , (reason) => {
        alert('再接再厉~号码为'+reason)

      })
      //catch方法是失败的回调函数
      .catch((reason) => {

      })

      // promise状态（实例对象中的一个属性PromiseState）
      // 1、pending(未决定的) 变为 resolved
      // 2、pending 变为 rejected
      // 只有这两种，且promise对象只能改变一次。无论变为成功还是失败，都会有一个结果数据。（成功的结果数据一般称为value，失败的结果数据一般称为reason）

      //promise 对象的值（实例中的另一个属性PromiseResult）
      //保存着对象 成功/失败 的结果
      //也就是resolve或rejexct方法中传入的值
    })
  </script>
</body>
</html>